/* eslint-disable @typescript-eslint/no-var-requires */
const { OFF, WARN, ERROR } = require('../constants');

module.exports = {
  plugins: ['react'],

  rules: {
    'react/boolean-prop-naming': OFF,
    'react/button-has-type': OFF,
    'react/default-props-match-prop-types': ERROR,
    'react/destructuring-assignment': OFF,
    'react/display-name': [ERROR, { ignoreTranspilerName: false }],
    'react/forbid-component-props': OFF,
    'react/forbid-dom-props': OFF,
    'react/forbid-elements': OFF,
    'react/forbid-foreign-prop-types': OFF,
    'react/forbid-prop-types': OFF,
    'react/jsx-boolean-value': OFF,
    'react/jsx-child-element-spacing': WARN,
    'react/jsx-curly-brace-presence': [WARN, { props: 'never', children: 'ignore' }],
    'react/jsx-curly-newline': OFF,
    'react/jsx-fragments': [ERROR, 'syntax'],
    'react/jsx-handler-names': ERROR,
    'react/jsx-key': ERROR,
    'react/jsx-max-depth': OFF,
    'react/jsx-no-bind': OFF,
    'react/jsx-no-comment-textnodes': ERROR,
    'react/jsx-no-duplicate-props': ERROR,
    'react/jsx-no-literals': OFF,
    'react/jsx-no-target-blank': ERROR,
    'react/jsx-no-undef': ERROR,
    'react/jsx-pascal-case': ERROR,
    'react/jsx-props-no-multi-spaces': OFF,
    'react/jsx-props-no-spreading': [OFF, { html: 'ignore', custom: 'ignore' }],
    'react/jsx-sort-default-props': ERROR,
    'react/jsx-sort-props': ERROR,
    'react/jsx-uses-react': ERROR,
    'react/jsx-uses-vars': ERROR,
    'react/no-access-state-in-setstate': ERROR,
    'react/no-array-index-key': ERROR,
    'react/no-children-prop': OFF,
    'react/no-danger-with-children': ERROR,
    'react/no-danger': OFF,
    'react/no-deprecated': ERROR,
    'react/no-did-mount-set-state': ERROR,
    'react/no-did-update-set-state': ERROR,
    'react/no-direct-mutation-state': ERROR,
    'react/no-find-dom-node': ERROR,
    'react/no-is-mounted': ERROR,
    'react/no-multi-comp': OFF,
    'react/no-redundant-should-component-update': ERROR,
    'react/no-render-return-value': ERROR,
    'react/no-set-state': OFF,
    'react/no-string-refs': ERROR,
    'react/no-this-in-sfc': ERROR,
    'react/no-typos': ERROR,
    'react/no-unescaped-entities': WARN,
    'react/no-unknown-property': ERROR,
    'react/no-unsafe': WARN,
    'react/no-unused-prop-types': ERROR,
    'react/no-unused-state': ERROR,
    'react/no-will-update-set-state': ERROR,
    'react/prefer-es6-class': OFF,
    'react/prefer-read-only-props': OFF,
    'react/prefer-stateless-function': ERROR,
    'react/prop-types': OFF,
    'react/react-in-jsx-scope': ERROR,
    'react/require-default-props': OFF,
    'react/require-optimization': OFF,
    'react/require-render-return': ERROR,
    'react/self-closing-comp': ERROR,
    'react/sort-comp': OFF,
    'react/sort-prop-types': ERROR,
    'react/state-in-constructor': [OFF, 'always'],
    'react/static-property-placement': [WARN],
    'react/style-prop-object': ERROR,
    'react/void-dom-elements-no-children': ERROR,
  },
};
